word_list=['electricity', 'donkey', 'hardware', 'xerox', 'transistor', 'computer', 'desktop'
 'engineering', 'hangman', 'circuit', 'imagination', 'robot', 'memory', 'power',
 'submarine', 'chess', 'resistance', 'matrix', 'function', 'laser', 'mechanism',
 'bodyguard', 'titanic', 'global', 'ozone', 'bridge', 'technology', 'spider',
 'pyramid', 'sphere', 'member', 'warning', 'yourself', 'screen', 'language',
 'system', 'internet', 'parameter', 'traffic', 'network', 'filter', 'nucleus',
 'automatic', 'microphone', 'cassette','pulchritude', 'defenestrate', 'sonder', 'ephemeral', 'limerence', 'petrichor', 'ineffable', 'susurrus', 'vellichor', 'clinomania',
'psithurism', 'apricity', 'numinous', 'penumbra', 'umbra', 'lucent', 'noctivagant', 'threnody', 'mellifluous', 'effervescent',
'eldritch', 'esoteric', 'arcane', 'cryptic', 'quixotic', 'labyrinthine', 'diaphanous', 'ethereal', 'evanescent', 'resplendent',
'palimpsest', 'chiaroscuro', 'verisimilitude', 'sonderzeit', 'hiraeth', 'reverie', 'transience', 'efflorescence', 'panoply', 'epiphany',
'cacophony', 'zephyr', 'glimmer', 'aureate', 'languor', 'threnos', 'susurration', 'fathomless', 'oracle', 'elixir',
'obfuscate', 'myriad', 'enigma', 'paradox', 'halcyon', 'idyllic', 'nebulous', 'oblivion', 'peregrinate', 'peregrination',
'serendipity', 'nostalgia', 'melancholia', 'solivagant', 'sonorous', 'luminous', 'emberglow', 'silhouette', 'afterglow', 'moonlit',
'harbinger', 'quintessence', 'ephemeralness', 'diurnal', 'nocturnal', 'astral', 'celestial', 'cosmic', 'starlit', 'twilight',
'labyrinth', 'mirage', 'spectral', 'phantasm', 'apparition', 'ethereality', 'immaterial', 'incandescent', 'radiance', 'brilliance',
'shimmer', 'iridescent', 'opalescent', 'translucent', 'gossamer', 'silken', 'featherlight', 'weightless', 'aerial', 'buoyant',
'stillness', 'hushed', 'whispered', 'murmur', 'rustle', 'flutter', 'drift', 'wanderlust', 'roam', 'meander',
'vagrant', 'nomadic', 'itinerant', 'wayfarer', 'travail', 'sojourn', 'odyssey', 'voyage','irruption', 'peregrinatory', 'solipsistic', 'ineluctable', 'pulchritudinous', 'recondite', 'abstruse', 'obstreperous', 'contumacious', 'magniloquent',
'perspicacious', 'grandiloquent', 'pusillanimous', 'vociferous', 'lugubrious', 'obfuscatory', 'sesquipedalian', 'circumlocution', 'perfidious', 'ignominious',
'parsimonious', 'profligate', 'intrepid', 'temerity', 'insouciant', 'equanimity', 'fortuitous', 'propitious', 'auspicious', 'salubrious',
'deleterious', 'pernicious', 'noxious', 'maleficent', 'baleful', 'venomous', 'insidious', 'nefarious', 'iniquitous', 'egregious',
'ubiquitous', 'omniscient', 'omnipotent', 'omnipresent', 'transubstantial', 'incorporeal', 'immortal', 'imperishable', 'indelible', 'ineffaceable',
'vicissitude', 'transience', 'ephemerality', 'mutability', 'flux', 'capriciousness', 'volatility', 'instability', 'impermanence', 'entropy',
'catharsis', 'apotheosis', 'transfiguration', 'metamorphosis', 'alchemy', 'transmutation', 'sublimation', 'crystallization', 'precipitation', 'distillation',
'axiomatic', 'dogmatic', 'heretical', 'iconoclastic', 'orthodox', 'canonical', 'esoteric', 'arcane', 'occult', 'mysticism',
'numinous', 'sacrosanct', 'consecrated', 'hallowed', 'sanctified', 'profane', 'blasphemous', 'irreverent', 'impious', 'heretical',
'zenith', 'nadir', 'apogee', 'perigee', 'culmination', 'acme', 'pinnacle', 'summit', 'crescendo', 'climax',
'lull', 'hiatus', 'interregnum', 'interlude', 'respite', 'reprieve', 'cessation', 'abeyance', 'suspension', 'stasis',
'maelstrom', 'whirlpool', 'vortex', 'tempest', 'typhoon', 'cyclone', 'deluge', 'torrent', 'downpour', 'inundation',
'cataclysm', 'catastrophe', 'calamity', 'havoc', 'ruination', 'desolation', 'devastation', 'annihilation', 'obliteration', 'extinction',
'relic', 'artifact', 'antiquity', 'vestige', 'remnant', 'trace', 'echo', 'afterimage', 'imprint', 'residue','ataraxia', 'eudaimonia', 'anomie', 'ennui', 'weltschmerz', 'saudade', 'sehnsucht', 'dolor', 'pathos', 'lachrymose',
'threnodic', 'lugubriousness', 'morbidity', 'morose', 'saturnine', 'sanguine', 'choleric', 'phlegmatic', 'melancholic', 'stoicism',
'ascetic', 'monastic', 'hermetic', 'reclusive', 'eremitic', 'anchorite', 'solitary', 'sequestered', 'cloistered', 'withdrawn',
'ineffability', 'indescribable', 'inexpressible', 'unspeakable', 'unutterable', 'wordless', 'mute', 'taciturn', 'reticent', 'reserved',
'propinquity', 'vicinity', 'adjacency', 'contiguity', 'proximity', 'nearness', 'closeness', 'intimacy', 'rapport', 'affinity',
'congruence', 'consonance', 'harmony', 'symmetry', 'equilibrium', 'balance', 'poise', 'stability', 'steadiness', 'composure',
'fluctuation', 'oscillation', 'undulation', 'vibration', 'pulsation', 'rhythm', 'cadence', 'tempo', 'beat', 'throb',
'verve', 'vitality', 'vivacity', 'zest', 'ardor', 'fervor', 'zeal', 'passion', 'intensity', 'fire',
'placid', 'serene', 'tranquil', 'quiescent', 'still', 'calm', 'peaceful', 'soothing', 'gentle', 'mild',
'rugged', 'craggy', 'jagged', 'gnarled', 'weathered', 'scarred', 'eroded', 'ravaged', 'worn', 'ancient',
'verdant', 'lush', 'fecund', 'flourishing', 'bountiful', 'fertile', 'teeming', 'abundant', 'plentiful', 'copious',
'attenuated', 'diluted', 'rarefied', 'tenuous', 'fragile', 'delicate', 'brittle', 'frail', 'breakable', 'perishable',
'colossal', 'monumental', 'titanic', 'gargantuan', 'immense', 'vast', 'enormous', 'boundless', 'limitless', 'infinite','crepuscular', 'vespertine', 'matutinal', 'auroral', 'noctilucent', 'tenebrous', 'umbrage', 'penumbral', 'shadowed', 'dusky',
'sepulchral', 'funereal', 'morbid', 'macabre', 'grim', 'dire', 'bleak', 'somber', 'dismal', 'forlorn',
'felicity', 'beatitude', 'bliss', 'rapture', 'ecstasy', 'elation', 'jubilation', 'exultation', 'glee', 'delight',
'precipitous', 'vertiginous', 'steep', 'sheer', 'towering', 'lofty', 'soaring', 'elevated', 'exalted', 'sublime',
'pristine', 'immaculate', 'unsullied', 'untainted', 'pure', 'spotless', 'flawless', 'incorruptible', 'unblemished', 'perfect',
'resonance', 'reverberation', 'echoic', 'sonic', 'acoustic', 'harmonic', 'vibratory', 'pulsative', 'rhythmic', 'cadential',
'labile', 'mutable', 'protean', 'shape-shifting', 'fluid', 'mercurial', 'changeable', 'unstable', 'fickle', 'inconstant',
'voracious', 'insatiable', 'ravenous', 'gluttonous', 'avid', 'hungry', 'greedy', 'rapacious', 'covetous', 'eager',
'eloquent','articulate', 'fluent', 'persuasive', 'expressive', 'rhetorical', 'oratorical', 'voluble', 'glib',
'furtive', 'stealthy', 'covert', 'surreptitious', 'clandestine', 'sly', 'sneaky', 'underhanded', 'secretive', 'hidden',
'arduous', 'onerous', 'gruelling', 'exacting', 'laborious', 'toilsome', 'strenuous', 'fatiguing', 'wearisome', 'draining',
'irreversible', 'irrevocable', 'unalterable', 'immutable', 'fixed', 'permanent', 'enduring', 'lasting', 'eternal', 'everlasting',
'harrowing', 'heartrending', 'poignant', 'moving', 'touching', 'emotive', 'affecting', 'stirring', 'powerful', 'intense','ultracrepidarian','floccinaucinihilipilification', 'sesquipedalianism', 'hippopotomonstrosesquipedaliophobia', 'quidnunc', 'snollygoster', 'pettifogger', 'gongoozler', 'cockalorum', 'ragamuffin',
'collywobbles', 'widdershins', 'absquatulate', 'skedaddle', 'bumbershoot', 'hornswoggle', 'nincompoop', 'fiddlefaddle', 'dillydally', 'lollygag',
'cattywampus', 'flapdoodle', 'balderdash', 'poppycock', 'tomfoolery', 'malarkey', 'hogwash', 'codswallop', 'drivel', 'nonsense',
'bedazzle', 'bamboozle', 'befuddle', 'confound', 'flummox', 'nonplus', 'perplex', 'stupefy', 'daze', 'astonish',
'scurvy', 'nefarious', 'rapscallion', 'scallywag', 'miscreant', 'rascal', 'rogue', 'villain', 'reprobate', 'ne’er-do-well',
'laggard', 'sluggard', 'shirker', 'idler', 'loafer', 'truant', 'vagabond', 'drifter', 'derelict', 'outcast',
'pellucid', 'lucubrate', 'perspicuity', 'clarion', 'effulgent', 'refulgent', 'resplendency', 'splendiferous', 'glister', 'coruscate',
'noisome', 'fetid', 'putrescent', 'miasmatic', 'rank', 'malodorous', 'reeking', 'pungent', 'acrid', 'stenchful',
'threnetic', 'frenetic', 'manic', 'rabid', 'hysterical', 'wild', 'frantic', 'berserk', 'unhinged', 'deranged',
'tenacious', 'dogged', 'relentless', 'indefatigable', 'assiduous', 'sedulous', 'untiring', 'ceaseless', 'inexorable', 'unyielding' 'expanse', 'horizon',
'infinity', 'eternity', 'timeless', 'boundless', 'limitless', 'vastness', 'abyss', 'chasm', 'depthless', 'void',
'cosmos', 'universe', 'firmament', 'heavens', 'constellation', 'nebula', 'galaxy', 'supernova', 'eclipse', 'orbit', 'operation', 'country', 'beautiful',
 'picture', 'teacher', 'superman', 'undertaker', 'alarm', 'process', 'keyboard',
 'electron', 'certificate', 'grandfather', 'landmark', 'relativity', 'eraser',
 'design', 'football', 'human', 'musician', 'egyptian', 'elephant', 'queen',
 'message', 'wallpaper', 'nationality', 'answer', 'wrong', 'statement', 'forest',
 'puzzle', 'voltage', 'current', 'mathematics', 'wisdom', 'dream', 'supermarket',
 'database', 'collection', 'barrier', 'project', 'sunlight', 'figure', 'graph',
 'battle', 'hundred', 'signal', 'thousand', 'transformation', 'daughter',
 'communication', 'microwave', 'electronic', 'peace', 'wireless', 'delete',
 'brain', 'control', 'prophet', 'freedom', 'harbour', 'confidence', 'positive',
 'harvest', 'hunger', 'woman', 'children', 'stranger', 'garden', 'pleasure',
 'between', 'recognition', 'tomorrow', 'autumn', 'monkey', 'spring', 'winter',
 'classification', 'typewriter', 'success', 'difference', 'acoustics',
 'agreement', 'sorrow', 'christmas', 'silver', 'birthday', 'championship', 'friend'
 'comfortable', 'diffusion', 'murder', 'policeman', 'science', 'desert', 'basketball'
 'blood', 'funeral', 'silence', 'garment', 'merchant', 'spirit', 'punishment', 'soap'
 'measurement', 'ocean', 'digital', 'illusion', 'tyrant', 'castle', 'passion', 'parrot'
 'magician', 'remedy', 'knowledge', 'threshold', 'number', 'vision', 'expectation'
 'absence', 'mystery', 'morning', 'device', 'thoughts', 'spirit', 'future',
 'mountain', 'treasure', 'machine', 'whispering', 'eternity', 'reflection',
 'achievement', 'lightning', 'secret', 'environment', 'shepherd', 'confusion',
 'grave', 'promise', 'honour', 'reward', 'temple', 'distance', 'eagle', 'saturn',
 'finger', 'belief', 'crystal', 'fashion', 'direction', 'captain', 'moment',
 'permission', 'logic', 'analysis', 'password', 'english', 'equalizer', 'simultaneously'
 'emotion', 'battle', 'expression', 'scissors', 'trousers', 'glasses', 'department',
 'dictionary', 'chemistry', 'induction', 'detail', 'widow', 'wealth', 'health',
 'disaster', 'volcano', 'poverty', 'limitation', 'perfect', 'intelligence', 'infinite'
 'failure', 'ignorance', 'destination', 'source', 'resort', 'satisfaction',
 'frequency', 'selection', 'substitution', 'kingdom', 'pattern', 'management',
 'situation', 'multiply', 'treatment', 'dollar', 'intuition', 'chapter', 'magnet'
 'desire', 'command', 'action', 'consciousness', 'enemy', 'security', 'object',
 'happen', 'happiness', 'worry', 'method', 'tolerance', 'error', 'hesitation',
 'record', 'tongue', 'supply', 'vibration', 'stress', 'despair', 'restaurant',
 'television', 'video', 'audio', 'layer', 'mixture', 'doorbell', 'cousin',
 'finance', 'production', 'invisible', 'excitement', 'afternoon', 'office',
 'illustration', 'valley', 'apartment', 'necessary', 'shortage', 'almost',
 'blanket', 'suggestion', 'overflow', 'demonstration', 'challenge', 'compact',
 'tower', 'question', 'problem', 'pressure', 'beast', 'encouragement', 'afraid',
 'cavity', 'appearance', 'wonderful', 'matter', 'dimension', 'business', 'doubt',
 'conversation', 'reaction', 'psychology', 'superstition', 'smash', 'horseshoe',
 'surprise', 'nothing', 'ladder', 'opposite', 'reality', 'genius', 'string',
 'destruction', 'expensive', 'painting', 'chicken', 'wishing', 'profession',
 'hatred', 'possession', 'criticism', 'zebra', 'harmony', 'personality', 'overcome'
 'addition', 'subtraction', 'cipher', 'encryption', 'compression', 'extension',
 'blessing', 'meeting', 'difficulty', 'weapon', 'against', 'external', 'internal'
 'legend', 'servant', 'secondary','attraction', 'sensitivity', 'magnification', 'someone', 'symptom', 'recipe',
 'service', 'family', 'island', 'planet', 'butterfly', 'diving', 'strength',
 'extreme', 'opportunity', 'illumination', 'cable', 'conflict', 'interference',
 'receiver', 'transmitter', 'channel', 'company', 'grocery', 'devil', 'angel',
 'exactly', 'document', 'tutorial', 'sound', 'voice', 'abbreviation', 'abdomen',
 'abrupt', 'absolute', 'absorption', 'abstract', 'academy', 'acceleration',
 'accident', 'account', 'acidification', 'actress', 'adaptation', 'addiction',
 'adjustment', 'admiration', 'adoption', 'advanced', 'adventure', 'advertisement'
 'agenda', 'airport', 'algorithm', 'allocation', 'aluminium', 'ambiguity',
 'amphibian', 'anaesthesia', 'analogy', 'anchor', 'animation', 'anode', 'cathode'
 'apparent', 'appendix', 'approval', 'approximation', 'arbitrary', 'architecture'
 'arithmetic', 'arrangement', 'article', 'ascending', 'ashamed', 'asleep',
 'assembly', 'astonishment', 'atmosphere', 'awful', 'bachelor', 'backbone',
 'bacteria', 'balance', 'balloon', 'banana', 'barbecue', 'baseball', 'beaker',
 'beggar', 'behaviour', 'benefit', 'bidirectional', 'biology', 'blackboard',
 'bladder', 'bleeding', 'blender', 'bonus', 'bottle', 'bracket', 'branch',
 'bubble', 'bucket', 'budget', 'bullet', 'burglar', 'butcher', 'bypass',
 'calculator', 'calibration', 'campaign', 'cancellation', 'candidate', 'candle',
 'carpenter', 'carriage', 'cartoon', 'cascade', 'casual', 'catalyst', 'category',
 'cement', 'ceremony', 'chairman', 'checkout', 'chimney', 'chocolate',
 'circumference', 'civilization', 'classroom', 'clearance', 'client', 'coconut',
 'coincidence', 'colleague', 'comfortable', 'competition', 'kangaroo', 'kidnap',
 'journal', 'jockey', 'iteration', 'isometric', 'isolation', 'invitation',
 'institution', 'injection', 'humanity', 'housekeeper', 'history', 'heaven',
 'greenhouse', 'glory', 'foundation', 'formula', 'fluctuation', 'fiction',
 'emission', 'elasticity', 'earthquake', 'dynamic', 'doctorate','hare','krishna','ram']